# Generated by Django 4.2.13 on 2024-06-24 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(default="bet")),
                ("total", models.IntegerField(default=100)),
                ("yes_label", models.CharField(default="yes", max_length=50)),
                ("no_label", models.CharField(default="no", max_length=50)),
                ("yes_ratio", models.FloatField(default=2)),
                ("no_ratio", models.FloatField(default=2)),
                ("open", models.BooleanField(default=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "started_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vote", models.CharField(choices=[("yes", "yes"), ("no", "no")], max_length=3, null=True)),
                ("amount", models.IntegerField()),
                ("did_win", models.BooleanField(default=False)),
                ("bet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bets.bet")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
