# Generated by Django 4.2.13 on 2024-07-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_rename_no_ratio_bet_ratio_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='total',
        ),
    ]
