# Generated by Django 4.2.13 on 2024-06-24 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bingo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("card", models.JSONField(blank=True)),
                ("completed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-date",),
                "unique_together": {("date", "card")},
            },
        ),
        migrations.CreateModel(
            name="BingoField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BingoEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("marked", models.BooleanField(default=False)),
                ("bingo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bingo.bingo")),
                ("bingo_field", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bingo.bingofield")),
            ],
        ),
    ]
