# Generated by Django 4.2.13 on 2024-07-01 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bingoentry",
            name="date",
        ),
        migrations.AddField(
            model_name="bingoentry",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
