# Generated by Django 4.2.13 on 2024-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patchnotes",
            name="title",
            field=models.CharField(default="Launch of app", max_length=100),
            preserve_default=False,
        ),
    ]
