# Generated by Django 4.2.13 on 2024-07-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("casino", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bells",
            fields=[
                (
                    "game_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="casino.game",
                    ),
                ),
            ],
            bases=("casino.game",),
        ),
        migrations.CreateModel(
            name="BlackJack",
            fields=[
                (
                    "game_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="casino.game",
                    ),
                ),
            ],
            bases=("casino.game",),
        ),
        migrations.CreateModel(
            name="Roulette",
            fields=[
                (
                    "game_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="casino.game",
                    ),
                ),
            ],
            bases=("casino.game",),
        ),
        migrations.RemoveField(
            model_name="game",
            name="symbols",
        ),
        migrations.AlterField(
            model_name="spin",
            name="game",
            field=models.CharField(
                choices=[
                    ("HighCard", "High Card"),
                    ("Roulette", "Roulette"),
                    ("BlackJack", "Black Jack"),
                    ("Bells", "Bells"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="HighCard",
        ),
    ]
