# Generated by Django 4.2.13 on 2024-07-08 06:31

from django.db import migrations


def adjust_spins(apps,schema_editor):
    Spin = apps.get_model("casino","Spin")
    winning_spins = Spin.objects.filter(has_won=True)
    for spin in winning_spins:
        spin.amount = spin.amount/1.4
        spin.save()



def reverse_spins(apps,schema_editor):
    Spin = apps.get_model("casino","Spin")
    winning_spins = Spin.objects.filter(has_won=True)
    for spin in winning_spins:
        spin.amount = spin.amount*1.4
        spin.save()
    return


class Migration(migrations.Migration):
    dependencies = [
        ("casino", "0003_highcard"),
    ]

    operations = [migrations.RunPython(adjust_spins, reverse_spins)]
